"""Orden de alta de los jugadores (F28, D-74)

`players.seq`: identidad que crece con cada alta. Es el desempate estable de las listas de
jugadores (bitácora, matrices, catálogos), como el orden de PLAYERS_SEED en el mockup; las
actualizaciones (ELO, color) no lo cambian. Backfill: por fecha de la primera partida (los que
nunca jugaron, al final) y luego por id, el mismo orden de la migración de colores.

Revision ID: a3b4c5d6e7f8
Revises: f2a3b4c5d6e7
Create Date: 2026-10-04 03:00:00.000000

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = 'a3b4c5d6e7f8'
down_revision: Union[str, Sequence[str], None] = 'f2a3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

_BACKFILL = sa.text("""
    UPDATE players p SET seq = o.n FROM (
        SELECT p.id, ROW_NUMBER() OVER (ORDER BY f.first NULLS LAST, p.id) AS n FROM players p
        LEFT JOIN (SELECT pr.player_id, MIN(g.date) AS first FROM player_results pr
                   JOIN games g ON g.id = pr.game_id GROUP BY pr.player_id) f ON f.player_id = p.id
    ) o WHERE o.id = p.id
""")


def upgrade() -> None:
    op.add_column("players", sa.Column("seq", sa.Integer(), nullable=True))
    op.execute(_BACKFILL)
    op.alter_column("players", "seq", nullable=False)
    op.execute("ALTER TABLE players ALTER COLUMN seq ADD GENERATED BY DEFAULT AS IDENTITY")
    op.execute("SELECT setval(pg_get_serial_sequence('players', 'seq'), COALESCE(MAX(seq), 0) + 1, false) FROM players")
    op.create_unique_constraint("uq_players_seq", "players", ["seq"])


def downgrade() -> None:
    op.drop_constraint("uq_players_seq", "players", type_="unique")
    op.drop_column("players", "seq")
