"""initial schema

Revision ID: a9ed5386f94f
Revises: 
Create Date: 2026-02-27 13:30:48.919865

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9ed5386f94f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('games',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('map_name', sa.Enum('HELLAS', 'THARSIS', 'ELYSIUM', 'BOREALIS', 'AMAZONIS', name='mapname'), nullable=False),
    sa.Column('expansions', sa.ARRAY(sa.Enum('PRELUDE', 'COLONIES', 'TURMOIL', 'VENUS_NEXT', name='expansion')), nullable=False),
    sa.Column('draft', sa.Boolean(), nullable=False),
    sa.Column('generations', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('players',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('awards',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('award_name', sa.Enum('TERRAFORMER', 'MAYOR', 'GARDENER', 'BUILDER', 'PLANNER', 'CULTIVATOR', 'MAGNATE', 'SPACE_BARON', 'EXCENTRIC', 'CONTRACTOR', 'CELEBRITY', 'INDUSTRIALIST', 'DESERT_SETTLER', 'ESTATE_DEALER', 'BENEFACTOR', name='award'), nullable=False),
    sa.Column('opened_by', sa.String(), nullable=False),
    sa.Column('first_place', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('second_place', sa.ARRAY(sa.String()), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opened_by'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('game_id', sa.String(), nullable=False),
    sa.Column('player_id', sa.String(), nullable=False),
    sa.Column('corporation', sa.Enum('CREDICOR', 'ECOLINE', 'HELION', 'INTERPLANETARY_CINEMATICS', 'INVENTRIX', 'MINING_GUILD', 'PHOBOLOG', 'SATURN_SYSTEMS', 'THARSIS_REPUBLIC', 'THORGATE', 'POINT_LUNA', 'ROBINSON_INDUSTRIES', 'VALLEY_TRUST', 'VITOR', 'ARCADIAN_COMMUNITIES', 'APHRODITE', 'CELESTIC', 'MANUTECH', 'MORNING_STAR_INC', 'VIRON', 'ARIDOR', 'POLYPHEMOS', 'POSEIDON', 'STORMCRAFT', 'TERRALABS_RESEARCH', 'SEPTEM_TRIBUS', 'SPLICE_TACTICAL_GENOMICS', 'TERACTOR', 'UTOPIA_INVEST', 'CHEUNG_SHING_MARS', 'FACTORUM', 'MONS_INSURANCE', 'RECYCLON', 'SAGITTA', name='corporation'), nullable=False),
    sa.Column('terraform_rating', sa.Integer(), nullable=False),
    sa.Column('milestone_points', sa.Integer(), nullable=False),
    sa.Column('milestones', sa.ARRAY(sa.Enum('TERRAFORMER', 'MAYOR', 'GARDENER', 'BUILDER', 'PLANNER', 'GENERALIST', 'SPECIALIST', 'ECOLOGIST', 'TYCOON', 'LEGEND', 'DIVERSIFIER', 'TACTICIAN', 'POLAR_EXPLORER', 'ENERGIZER', 'RIM_SETTLER', name='milestone')), nullable=False),
    sa.Column('award_points', sa.Integer(), nullable=False),
    sa.Column('card_points', sa.Integer(), nullable=False),
    sa.Column('card_resource_points', sa.Integer(), nullable=False),
    sa.Column('greenery_points', sa.Integer(), nullable=False),
    sa.Column('city_points', sa.Integer(), nullable=False),
    sa.Column('turmoil_points', sa.Integer(), nullable=True),
    sa.Column('mc_total', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_results')
    op.drop_table('awards')
    op.drop_table('players')
    op.drop_table('games')
    # ### end Alembic commands ###
